#This file goes with keyboard.py.
#This file contains the letter sets for the program.

greek = [
    'theta',
    'omega',
    'epsilon',
    'rho',
    'tau',
    'psi',
    'upsilon',
    'iota',
    'omicron',
    'pi',

    'alpha',
    'sigma',
    'delta',
    'phi',
    'gamma',
    'eta',
    'xi',
    'kappa',
    'lamda',
    'question',

    'zeta',
    'chi',
    'nu',
    'beta',
    'mu',
    'final sigma'
]

greekLetters = {
    'alpha':[u'\u0391',u'\u03B1'],
    'beta':[u'\u0392',u'\u03B2'],
    'gamma':[u'\u0393',u'\u03B3'],
    'delta':[u'\u0394',u'\u03B4'],
    'epsilon':[u'\u0395',u'\u03B5'],
    'zeta':[u'\u0396',u'\u03B6'],
    'eta':[u'\u0397',u'\u03B7'],
    'theta':[u'\u0398',u'\u03B8'],
    'iota':[u'\u0399',u'\u03B9'],
    'kappa':[u'\u039A',u'\u03BA'],
    'lamda':[u'\u039B',u'\u03BB'],
    'mu':[u'\u039C',u'\u03BC'],
    'nu':[u'\u039D',u'\u03BD'],
    'xi':[u'\u039E',u'\u03BE'],
    'omicron':[u'\u039F',u'\u03BF'],
    'pi':[u'\u03A0',u'\u03C0'],
    'rho':[u'\u03A1',u'\u03C1'],
    'final sigma':[u'\u03C2',u'\u03C2'],
    'sigma':[u'\u03A3',u'\u03C3'],
    'tau':[u'\u03A4',u'\u03C4'],
    'upsilon':[u'\u03A5',u'\u03C5'],
    'phi':[u'\u03A6',u'\u03C6'],
    'chi':[u'\u03A7',u'\u03C7'],
    'psi':[u'\u03A8',u'\u03C8'],
    'omega':[u'\u03A9',u'\u03C9'],
    'question':[u'\u037E',u'\u037E']
}

english = [
    '1','2','3','4','5','6','7','8','9','0',
    'q','w','e','r','t','y','u','i','o','p',
    'a','s','d','f','g','h','j','k','l',';',
    'z','x','c','v','b','n','m'
]

englishLetters = {
    '1':['!','1'],
    '2':['@','2'],
    '3':['#','3'],
    '4':['$','4'],
    '5':['%','5'],
    '6':['^','6'],
    '7':['&','7'],
    '8':['*','8'],
    '9':['(','9'],
    '0':[')','0'],
    'a':['A','a'],
    'b':['B','b'],
    'c':['C','c'],
    'd':['D','d'],
    'e':['E','e'],
    'f':['F','f'],
    'g':['G','g'],
    'h':['H','h'],
    'i':['I','i'],
    'j':['J','j'],
    'k':['K','k'],
    'l':['L','l'],
    'm':['M','m'],
    'n':['N','n'],
    'o':['O','o'],
    'p':['P','p'],
    'q':['Q','q'],
    'r':['R','r'],
    's':['S','s'],
    't':['T','t'],
    'u':['U','u'],
    'v':['V','v'],
    'w':['W','w'],
    'x':['X','x'],
    'y':['Y','y'],
    'z':['Z','z'],
    ';':[':',':']
}

symbols = [
    #logic
    'and',
    'or',
    'not',
    'xor',
    'equivalent',
    'ifthen',
    'leftifthen',
    'iff',
    'thereexists',
    'forall',
    'therefore',

    #other stuff
    'lceil',
    'rceil',
    'lfloor',
    'rfloor',
    'reals',
    'ints',
    'naturals',
    'rationals',
    'irrationals',

    #sets
    'emptyset',
    'elementof',
    'notelementof',
    'subset',
    'superset',
    'notsubset',
    'notsuperset',
    'subsetorequal',
    'supersetorequal',
    'notsubsetorequal',
    'notsupersetorequal',
    
    #math
    'notequal',
    'approx',
    'lessequal',
    'greaterequal',
    'plusminus',
    'obelus',
    'times',
    'sqrt',
    'integral',
    'infinity',
    'sum',
    'pi',
    'delta',
    'bell'
]

symbolLetters = {
    #logic
    'and':[u'\u2227'],
    'or':[u'\u2228'],
    'not':[u'\u00AC'],
    'xor':[u'\u2295'],
    'equivalent':[u'\u2261'],
    'ifthen':[u'\u2192'],
    'leftifthen':[u'\u2190'],
    'iff':[u'\u2194'],
    'thereexists':[u'\u2203'],
    'forall':[u'\u2200'],
    'therefore':[u'\u2234'],

    #other stuff
    'lceil':[u'\u2308'],
    'rceil':[u'\u2309'],
    'lfloor':[u'\u230A'],
    'rfloor':[u'\u230B'],
    'reals':[u'\u211D'],
    'ints':[u'\u2124'],
    'naturals':[u'\u2115'],
    'rationals':[u'\u211A'],
    'irrationals':[u'\u2119'],
    
    #sets
    'emptyset':[u'\u2205'],
    'elementof':[u'\u2208'],
    'notelementof':[u'\u2209'],
    'subset':[u'\u2282'],
    'superset':[u'\u2283'],
    'notsubset':[u'\u2284'],
    'notsuperset':[u'\u2285'],
    'subsetorequal':[u'\u2286'],
    'supersetorequal':[u'\u2287'],
    'notsubsetorequal':[u'\u2288'],
    'notsupersetorequal':[u'\u2289'],
    
    #math
    'notequal':[u'\u2260'],
    'approx':[u'\u2248'],
    'plusminus':[u'\u00B1'],
    'obelus':[u'\u00F7'],
    'lessequal':[u'\u2264'],
    'greaterequal':[u'\u2265'],
    'integral':[u'\u222B'],
    'sqrt':[u'\u221A'],
    'infinity':[u'\u221E'],
    'sum':[u'\u2211'],
    'pi':[u'\u03C0'],
    'delta':[u'\u2206'],
    'times':[u'\u2219'],
    'bell':[u'\u0007']
}

circles = [
    'Q','W','E','R','T','Y','U','I','O','P',
    'A','S','D','F','G','H','J','K','L','0',
    'Z','X','C','V','B','N','M'
]
circledLetters = {
    'A':[u'\u24b6',u'\u24d0'],
    'B':[u'\u24b7',u'\u24d1'],
    'C':[u'\u24b8',u'\u24d2'],
    'D':[u'\u24b9',u'\u24d3'],
    'E':[u'\u24ba',u'\u24d4'],
    'F':[u'\u24bb',u'\u24d5'],
    'G':[u'\u24bc',u'\u24d6'],
    'H':[u'\u24bd',u'\u24d7'],
    'I':[u'\u24be',u'\u24d8'],
    'J':[u'\u24bf',u'\u24d9'],
    'K':[u'\u24c0',u'\u24da'],
    'L':[u'\u24c1',u'\u24db'],
    'M':[u'\u24c2',u'\u24dc'],
    'N':[u'\u24c3',u'\u24dd'],
    'O':[u'\u24c4',u'\u24de'],
    'P':[u'\u24c5',u'\u24df'],
    'Q':[u'\u24c6',u'\u24e0'],
    'R':[u'\u24c7',u'\u24e1'],
    'S':[u'\u24c8',u'\u24e2'],
    'T':[u'\u24c9',u'\u24e3'],
    'U':[u'\u24ca',u'\u24e4'],
    'V':[u'\u24cb',u'\u24e5'],
    'W':[u'\u24cc',u'\u24e6'],
    'X':[u'\u24cd',u'\u24e7'],
    'Y':[u'\u24ce',u'\u24e8'],
    'Z':[u'\u24cf',u'\u24e9'],
    '0':[u'\u263a',u'\u263a']
    
}
